---
language: bash
services: docker

env:
  - VERSION=2.5
  - VERSION=2.4 LATEST=true
  - VERSION=2.3
  - VERSION=2.2
  - VERSION=2.0
  - VERSION=1.9

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

before_script:
  - env | sort
  - export IMAGE="mini/ansible:${VERSION}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build -t "$IMAGE" $VERSION/
      IMAGE=$IMAGE VERSION=$VERSION bats tests/
    )

after_script:
  - docker images

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
